# Synthea sources to be used when not using the demonstration seeds
version: 2

sources:
  - name: vocab
    schema: dev_vc
    tables:
      - name: concept
      - name: concept_ancestor
      - name: concept_class
      - name: concept_relationship
      - name: concept_synonym
      - name: domain
      - name: relationship
      - name: source_to_concept_map
      - name: vocabulary
