version: 2

models:
  - name: person
    columns:
      - name: person_id
        description: "A unique identifier for each person."
        tests:
          - unique
          - not_null
      - name: gender_concept_id
        tests:
          - not_null
      - name: year_of_birth
        description: "The year of birth of the person."
        tests:
          - not_null
      - name: month_of_birth
        description: "The month of birth of the person."
      - name: day_of_birth
        description: "The day of birth of the person."
      - name: birth_datetime
        description: "The date and time of birth of the person."
      - name: race_concept_id
        tests:
          - not_null
      - name: ethnicity_concept_id
        tests:
          - not_null
      - name: location_id
        description: "A foreign key to the location table."
      - name: provider_id
        description: "A foreign key to the provider table."
      - name: care_site_id
        description: "A foreign key to the care site table."
      - name: person_source_value
      - name: gender_source_value
      - name: gender_source_concept_id
      - name: race_source_value
      - name: race_source_concept_id
      - name: ethnicity_source_value
      - name: ethnicity_source_concept_id
