project: 'sqlmesh_synthea'

gateways:
    local:
        connection:
            type: duckdb
            catalogs:
                persistent: './data/synthea_omop.duckdb'
                ephemeral: ':memory:'
        state_connection:
            type: duckdb
            catalogs:
                persistent: './data/sqlmesh_state.duckdb'
        
variables:
  schema_synthea: synthea
  schema_vocab: vocab
  schema_omop: omop
  schema_staging: staging

default_gateway: local

model_defaults:
    dialect: databricks
