# This file was created automatically by running sqlmesh create_external_models after running bootstrap.py
# The only modification post-creation was to change the data type for all CODE columns to TEXT
# ToDo: Ensure correct datatypes are enforced in bootstrap so that create_external_models 'just works'
# A way to do this would be to use https://github.com/OHDSI/ETL-Synthea/blob/main/inst/sql/sql_server/synthea_version/v270/create_synthea_tables.sql
- name: '"synthea"."allergies"'
  columns:
    START: DATE
    STOP: TEXT
    PATIENT: TEXT
    ENCOUNTER: TEXT
    CODE: TEXT
    SYSTEM: TEXT
    DESCRIPTION: TEXT
    TYPE: TEXT
    CATEGORY: TEXT
    REACTION1: BIGINT
    DESCRIPTION1: TEXT
    SEVERITY1: TEXT
    REACTION2: BIGINT
    DESCRIPTION2: TEXT
    SEVERITY2: TEXT
- name: '"synthea"."claims"'
  columns:
    Id: TEXT
    PATIENTID: TEXT
    PROVIDERID: TEXT
    PRIMARYPATIENTINSURANCEID: TEXT
    SECONDARYPATIENTINSURANCEID: TEXT
    DEPARTMENTID: BIGINT
    PATIENTDEPARTMENTID: BIGINT
    DIAGNOSIS1: BIGINT
    DIAGNOSIS2: BIGINT
    DIAGNOSIS3: BIGINT
    DIAGNOSIS4: BIGINT
    DIAGNOSIS5: BIGINT
    DIAGNOSIS6: TEXT
    DIAGNOSIS7: TEXT
    DIAGNOSIS8: TEXT
    REFERRINGPROVIDERID: TEXT
    APPOINTMENTID: TEXT
    CURRENTILLNESSDATE: TIMESTAMP
    SERVICEDATE: TIMESTAMP
    SUPERVISINGPROVIDERID: TEXT
    STATUS1: TEXT
    STATUS2: TEXT
    STATUSP: TEXT
    OUTSTANDING1: DOUBLE
    OUTSTANDING2: BIGINT
    OUTSTANDINGP: DOUBLE
    LASTBILLEDDATE1: TIMESTAMP
    LASTBILLEDDATE2: TIMESTAMP
    LASTBILLEDDATEP: TIMESTAMP
    HEALTHCARECLAIMTYPEID1: BIGINT
    HEALTHCARECLAIMTYPEID2: BIGINT
- name: '"synthea"."claims_transactions"'
  columns:
    ID: TEXT
    CLAIMID: TEXT
    CHARGEID: BIGINT
    PATIENTID: TEXT
    TYPE: TEXT
    AMOUNT: DOUBLE
    METHOD: TEXT
    FROMDATE: TIMESTAMP
    TODATE: TIMESTAMP
    PLACEOFSERVICE: TEXT
    PROCEDURECODE: TEXT
    MODIFIER1: TEXT
    MODIFIER2: TEXT
    DIAGNOSISREF1: BIGINT
    DIAGNOSISREF2: BIGINT
    DIAGNOSISREF3: BIGINT
    DIAGNOSISREF4: BIGINT
    UNITS: BIGINT
    DEPARTMENTID: BIGINT
    NOTES: TEXT
    UNITAMOUNT: DOUBLE
    TRANSFEROUTID: BIGINT
    TRANSFERTYPE: TEXT
    PAYMENTS: DOUBLE
    ADJUSTMENTS: TEXT
    TRANSFERS: DOUBLE
    OUTSTANDING: DOUBLE
    APPOINTMENTID: TEXT
    LINENOTE: TEXT
    PATIENTINSURANCEID: TEXT
    FEESCHEDULEID: BIGINT
    PROVIDERID: TEXT
    SUPERVISINGPROVIDERID: TEXT
- name: '"synthea"."conditions"'
  columns:
    START: DATE
    STOP: DATE
    PATIENT: TEXT
    ENCOUNTER: TEXT
    CODE: TEXT
    DESCRIPTION: TEXT
- name: '"synthea"."devices"'
  columns:
    START: TIMESTAMP
    STOP: TEXT
    PATIENT: TEXT
    ENCOUNTER: TEXT
    CODE: TEXT
    DESCRIPTION: TEXT
    UDI: TEXT
- name: '"synthea"."encounters"'
  columns:
    Id: TEXT
    START: TIMESTAMP
    STOP: TIMESTAMP
    PATIENT: TEXT
    ORGANIZATION: TEXT
    PROVIDER: TEXT
    PAYER: TEXT
    ENCOUNTERCLASS: TEXT
    CODE: TEXT
    DESCRIPTION: TEXT
    BASE_ENCOUNTER_COST: DOUBLE
    TOTAL_CLAIM_COST: DOUBLE
    PAYER_COVERAGE: DOUBLE
    REASONcode: TEXT
    REASONDESCRIPTION: TEXT
- name: '"synthea"."immunizations"'
  columns:
    DATE: TIMESTAMP
    PATIENT: TEXT
    ENCOUNTER: TEXT
    CODE: TEXT
    DESCRIPTION: TEXT
    BASE_COST: DOUBLE
- name: '"synthea"."medications"'
  columns:
    START: TIMESTAMP
    STOP: TIMESTAMP
    PATIENT: TEXT
    PAYER: TEXT
    ENCOUNTER: TEXT
    CODE: TEXT
    DESCRIPTION: TEXT
    BASE_COST: DOUBLE
    PAYER_COVERAGE: DOUBLE
    DISPENSES: BIGINT
    TOTALCOST: DOUBLE
    REASONcode: TEXT
    REASONDESCRIPTION: TEXT
- name: '"synthea"."observations"'
  columns:
    DATE: TIMESTAMP
    PATIENT: TEXT
    ENCOUNTER: TEXT
    CATEGORY: TEXT
    CODE: TEXT
    DESCRIPTION: TEXT
    VALUE: TEXT
    UNITS: TEXT
    TYPE: TEXT
- name: '"synthea"."patients"'
  columns:
    Id: TEXT
    BIRTHDATE: DATE
    DEATHDATE: DATE
    SSN: TEXT
    DRIVERS: TEXT
    PASSPORT: TEXT
    PREFIX: TEXT
    FIRST: TEXT
    LAST: TEXT
    SUFFIX: TEXT
    MAIDEN: TEXT
    MARITAL: TEXT
    RACE: TEXT
    ETHNICITY: TEXT
    GENDER: TEXT
    BIRTHPLACE: TEXT
    ADDRESS: TEXT
    CITY: TEXT
    STATE: TEXT
    COUNTY: TEXT
    ZIP: TEXT
    LAT: DOUBLE
    LON: DOUBLE
    HEALTHCARE_EXPENSES: DOUBLE
    HEALTHCARE_COVERAGE: DOUBLE
- name: '"synthea"."payer_transitions"'
  columns:
    PATIENT: TEXT
    MEMBERID: TEXT
    START_DATE: TIMESTAMP
    END_DATE: TIMESTAMP
    PAYER: TEXT
    SECONDARY_PAYER: TEXT
    PLAN_OWNERSHIP: TEXT
    OWNER_NAME: TEXT
- name: '"synthea"."payers"'
  columns:
    Id: TEXT
    NAME: TEXT
    ADDRESS: TEXT
    CITY: TEXT
    STATE_HEADQUARTERED: TEXT
    ZIP: BIGINT
    PHONE: TEXT
    AMOUNT_COVERED: DOUBLE
    AMOUNT_UNCOVERED: DOUBLE
    REVENUE: DOUBLE
    COVERED_ENCOUNTERS: BIGINT
    UNCOVERED_ENCOUNTERS: BIGINT
    COVERED_MEDICATIONS: BIGINT
    UNCOVERED_MEDICATIONS: BIGINT
    COVERED_PROCEDURES: BIGINT
    UNCOVERED_PROCEDURES: BIGINT
    COVERED_IMMUNIZATIONS: BIGINT
    UNCOVERED_IMMUNIZATIONS: BIGINT
    UNIQUE_CUSTOMERS: BIGINT
    QOLS_AVG: DOUBLE
    MEMBER_MONTHS: BIGINT
- name: '"synthea"."procedures"'
  columns:
    START: TIMESTAMP
    STOP: TIMESTAMP
    PATIENT: TEXT
    ENCOUNTER: TEXT
    CODE: TEXT
    DESCRIPTION: TEXT
    BASE_COST: DOUBLE
    REASONcode: TEXT
    REASONDESCRIPTION: TEXT
- name: '"synthea"."providers"'
  columns:
    Id: TEXT
    ORGANIZATION: TEXT
    NAME: TEXT
    GENDER: TEXT
    SPECIALITY: TEXT
    ADDRESS: TEXT
    CITY: TEXT
    STATE: TEXT
    ZIP: TEXT
    LAT: DOUBLE
    LON: DOUBLE
    UTILIZATION: BIGINT
- name: '"vocab"."concept"'
  columns:
    concept_id: BIGINT
    concept_name: TEXT
    domain_id: TEXT
    vocabulary_id: TEXT
    concept_class_id: TEXT
    standard_concept: TEXT
    concept_code: TEXT
    valid_start_date: BIGINT
    valid_end_date: BIGINT
    invalid_reason: TEXT
- name: '"vocab"."concept_ancestor"'
  columns:
    ancestor_concept_id: BIGINT
    descendant_concept_id: BIGINT
    min_levels_of_separation: BIGINT
    max_levels_of_separation: BIGINT
- name: '"vocab"."concept_relationship"'
  columns:
    concept_id_1: BIGINT
    concept_id_2: BIGINT
    relationship_id: TEXT
    valid_start_date: BIGINT
    valid_end_date: BIGINT
    invalid_reason: TEXT
- name: '"vocab"."vocabulary"'
  columns:
    vocabulary_id: TEXT
    vocabulary_name: TEXT
    vocabulary_reference: TEXT
    vocabulary_version: TEXT
    vocabulary_concept_id: BIGINT
